services:
  logic:
    container_name: logic
    build: .
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      - ./:/app:Z
      # Pastikan anonymous volume untuk node_modules mengarah ke /app
      - /app/node_modules
    depends_on:
      - logic-psql
      - redis

  logic-psql:
    image: docker.io/library/postgres:16-alpine
    container_name: logic-psql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=logic-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - logic-db:/var/lib/postgresql/data:Z

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: logic-redis
    redis_password: root
    restart: unless-stopped

volumes:
  logic-db:
